---
- name: install LAMP stack
  apt: name={{ item }} state=present
  with_items:
  - apache2
  - php5
  - php5-cli
  - php5-mcrypt
  - php5-gd
  - libssh2-php
  - php5-sqlite
  - php5-curl
  - php5-dev
  - php-pear
  - php5-memcache
  - php5-memcached
  - php5-tidy
  - libapache2-mod-rpaf

- name: enable modules
  apache2_module: name={{ item }} state=present
  with_items:
    - expires
    - headers
    - rewrite
    - rpaf
- name: Enable site
  command: a2ensite 000-default

- name: Copy over Apache configuration
  copy: src=default dest=/etc/apache2/sites-available/000-default.conf owner=root group=root mode=0644

- name: Ensure group www-data exists
  group: name=www-data state=present

- name: change apache webroot permissions
  file: path=/var/www state=directory recurse=yes mode="g+w" owner=www-data

- name: Restart Apache
  service: name=apache2 state=restarted

- name: remove default apache page
  file: path=/var/www/html state=absent
