---
- name: Update system
  apt: upgrade=full update_cache=yes

- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
   - python3
   - python3-dev
   - python3-pyvenv
   - python3-pip
   - supervisor
