---
- name: Set up a standard Laravel install
  hosts: laravel
  become: True

- name: Create new droplet
  roles:
    - create_droplet

- name: Set up utilities
  roles:
    - utilities

- name: Set up user
  roles:
    - users

- name: Set up Postgres
  roles:
    - postgres

- name: Set up Nginx and PHP
  roles:
    - nginx-php

- name: Set up firewall
  roles:
    - nginx_firewall

- name: Set up Redis
  roles:
    - redis
