---
- name: Set up a standard Laravel install
  hosts: localhost
  vars_prompt:
    - name: "domain"
      prompt: "Domain name"
      private: no
  roles:
    - create_droplet
    - create_domain
- name: Install dependencies
  hosts: launched
  roles:
    - utilities
    - users
    - nginx-php
    - nginx_firewall
    - redis
    - postgres
