---
- name: Set up a standard Laravel install
  hosts: localhost
  roles:
    - create_droplet
    - create_domain
- name: Install dependencies
  hosts: launched
  roles:
    - utilities
    - users
    - nginx-php
    - nginx_firewall
    - redis
    - postgres
