---
- name: Set up a standard Laravel install
  hosts: localhost
  vars_prompt:
    - name: "domain"
      prompt: "Domain name"
      private: no
    - name: "dbname"
      prompt: "Database name"
      private: no
    - name: "dbuser"
      prompt: "Database username"
      private: no
    - name: "dbpassword"
      prompt: "Database password"
      private: no
  roles:
    - create_droplet
    - create_domain
- name: Install dependencies
  hosts: launched
  roles:
    - upgrade
    - utilities
    - users
    - nginx-php
    - composer
    - nginx_firewall
    - redis
    - postgres
    - git
